<?php

	//Default Array for Form generation
	$form_values = array(
						'form-id'			=> 'make_form',
						'form-name'			=> 'wc-form',
						'form-classes' 		=> 'wc-make-form',
						'form-action'		=> 'self',
						'submit-label'		=> __('Save!', 'dealercrm'),
						'submit-classes'	=> 'btn btn-primary',
						'insert'			=> TRUE,
						'update'			=> FALSE, //If set true, make sure INSERT is set False. And Update_key is present.
						'update_key'		=> '', 
						'database-table'	=> 'make',
						'primary_column'	=> 'make_id',
						'auto_submit_form'	=> TRUE,
						'form-fields'	=> array(
								array( //Text Field
									'field-label'		=> __('Text Field Sample', 'dealercrm'),
									'field-name'		=> 'make_name',
									'db_duplicate'		=> FALSE,
									'field-type'		=> 'text',
									'field-desc'		=> 'Enter the make name cannot duplicate',
									'field-placeholder'	=> 'Make Name here',
									'field-required'	=> TRUE,
									'wrapper-classes'	=> 'make-wrapper',
									'wrapper-id'		=> 'make_wrapper',
									'field-columns'		=> '1',
									'field-value'		=> '',
								),
								array( //textarea
									'field-label'		=> _('Note Detail')." *",
									'field-name'		=> 'make_detail',
									'db_duplicate'		=> FALSE,
									'field-type'		=> 'textarea',
									'field-desc'		=> _('Your Note Detail'),
									'field-placeholder'	=> _('Enter Note Detail'),
									'field-required'	=> TRUE,
									'wrapper-classes'	=> 'note-wrapper tinyst',
									'wrapper-id'		=> 'note_wrapper',
									'field-columns'		=> '1',
									'field-value'		=> '',
								),
								array( //Hidden Field
									'field-name'		=> 'note_date',
									'db_duplicate'		=> TRUE,
									'field-type'		=> 'hidden',
									'field-required'	=> TRUE,
									'field-value'		=> time(),
								),
								array( // Email Field
									'field-label'		=> __('Email Sample', 'dealercrm'),
									'field-name'		=> 'make_name',
									'db_duplicate'		=> FALSE,
									'field-type'		=> 'email',
									'field-desc'		=> 'Enter the make name cannot duplicate',
									'field-placeholder'	=> 'Make Name here',
									'field-required'	=> TRUE,
									'wrapper-classes'	=> 'make-wrapper',
									'wrapper-id'		=> 'make_wrapper',
									'field-columns'		=> '1',
									'field-value'		=> '',
								),
								array( //Phone Field
									'field-label'		=> __('Phone Sample', 'dealercrm'),
									'field-name'		=> 'make_name',
									'db_duplicate'		=> FALSE,
									'field-type'		=> 'phone',
									'field-desc'		=> 'Enter the make name cannot duplicate',
									'field-placeholder'	=> 'Make Name here',
									'field-required'	=> TRUE,
									'wrapper-classes'	=> 'make-wrapper',
									'wrapper-id'		=> 'make_wrapper',
									'field-columns'		=> '1',
									'field-value'		=> '',
								),
								array( //Password Field
									'field-label'		=> __('Password Sample', 'dealercrm'),
									'field-name'		=> 'make_name',
									'db_duplicate'		=> FALSE,
									'field-type'		=> 'password',
									'field-desc'		=> 'Enter the make name cannot duplicate',
									'field-placeholder'	=> 'Make Name here',
									'field-required'	=> TRUE,
									'wrapper-classes'	=> 'make-wrapper',
									'wrapper-id'		=> 'make_wrapper',
									'field-columns'		=> '1',
									'field-value'		=> '',
								),
								array( //Select Field
									'field-label'		=> __('Select Make', 'dealercrm'),
									'field-name'		=> 'make_id',
									'db_duplicate'		=> true,
									'field-type'		=> 'select',
									'select-array'		=> array(
																array(
																	'option_value'	=> '1',
																	'option_label'	=> 'Toyota',
																	'selected'		=> TRUE,
																),
																array(
																	'option_value'	=> '1',
																	'option_label'	=> 'Toyota',
																	'selected'		=> FALSE,
																),
																array(
																	'option_value'	=> '1',
																	'option_label'	=> 'Toyota',
																	'selected'		=> FALSE,
																)
									),
									'field-required'	=> TRUE,
									'wrapper-classes'	=> 'make-wrapper',
									'wrapper-id'		=> 'make_wrapper',
									'field-columns'		=> '1',
								),
								array(
									'field-label'		=> __('Select Model', 'dealercrm'),
									'field-name'		=> 'model_id',
									'db_duplicate'		=> FALSE,
									'duplicate_join'	=> 'and', // Will compare with all available And operators in submission for table. Accepts or and and also
									'field-type'		=> 'select',
									'select-array'		=> $forms_obj->wc_generate_options_array("model", "model_id", "model_name", "", "", ""),
									'field-required'	=> TRUE,
									'wrapper-classes'	=> 'model-wrapper',
									'wrapper-id'		=> 'model_wrapper',
									'field-columns'		=> '1'
								),
								array(
									'field-label'		=> __('Model Year', 'dealercrm'),
									'field-name'		=> 'model_year',
									'db_duplicate'		=> FALSE,
									'duplicate_join'	=> 'and', // Will compare with all available And operators in submission for table. Accepts or and and also
									'field-type'		=> 'text',
									'field-desc'		=> 'Enter the Model Year cannot duplicate with model only number allowed',
									'field-placeholder'	=> '2009',
									'field-required'	=> TRUE,
									'wrapper-classes'	=> 'model-year-wrapper',
									'wrapper-id'		=> 'model_year_wrapper',
									'field-columns'		=> '1',
									'field-value'		=> '',
								),
								array(
									'field-label'		=> __('Select Vehicle Image', 'dealercrm'),
									'field-name'		=> 'car_image',
									'db_duplicate'		=> TRUE, //Duplicate Data is accepted
									'field-type'		=> 'upload',
									'field-placeholder'	=> __("Upload your car image", "dealercrm"),
									'field-required'	=> FALSE,
									'wrapper-classes'	=> 'form-row model-year-wrapper',
									'wrapper-id'		=> 'model_year_wrapper',
									'field-columns'		=> '1'
								),
								array(
										'field-label'		=> __('Select Make', 'dealercrm'),
										'field-name'		=> 'make_id',
										'db_duplicate'		=> true,
										'field-type'		=> 'select',
										'select-array'		=> $forms_obj->wc_generate_options_array("account_groups", "group_id", "group_title", _("Select Parent"), "", array("parent_id", "company_id"), array("NULL", $_SESSION["company_id"])),
										'field-required'	=> TRUE,
										'wrapper-classes'	=> 'make-wrapper',
										'wrapper-id'		=> 'make_wrapper',
										'field-columns'		=> '1',
										'field-value'		=> FALSE //FALSE VALUE WILL NOT RETURN ANY VALUE. NO matter update form is being created or INSERT
								),
						)
	);

	return $forms_obj->wc_form_generator($form_values);